apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: r83ysw4ap-python 
  janus-idp.io/tekton: r83ysw4ap-python
  backstage.io/kubernetes-id: r83ysw4ap-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r83ysw4ap-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  